<?php
const LUCENT_DB_BINARY = 1;
const LUCENT_DB_TINY_INT= 2;
const LUCENT_DB_DECIMAL = 3;
const LUCENT_DB_INT = 4;
const LUCENT_DB_JSON = 5;
const LUCENT_DB_TIMESTAMP = 6;

const LUCENT_DB_ENUM = 7;

const LUCENT_DB_DATE = 8;
const LUCENT_DB_TEXT = 10;

const LUCENT_DB_VARCHAR = 12;

const LUCENT_DB_DEFAULT_CURRENT_TIMESTAMP = "CURRENT_TIMESTAMP";